### ISSUE TITLE
插件首页能给个编辑功能吗？自由删除或者添加固定

### ISSUE THREAD

**Issue by GEEKCX** [extrastu/side-browser-release#1]
首页的网页卡片右顶部加入删除按钮，最好还能添加拖动排序啥的

**Comment by extrastu** [comment]
你好，访问过的网页会出现在 Recent Sites ，删除倒是可以加下 

![image](https://github.com/extrastu/side-browser-release/assets/19451694/ba927315-bf65-469a-b1f4-a400c1671502)

**Comment by extrastu** [comment]
1.0.6已经支持（最新是1.0.8
