### ISSUE TITLE
edge无法使用该插件

### ISSUE THREAD

**Issue by KainanSu** [extrastu/side-browser-release#2]
egde 版本 113.0.1774.50 (正式版本) (64 位)
点击插件无响应，右键也没有open In tab选项

**Comment by extrastu** [comment]
@KainanSu 你是从chrome商店安装的还是下载的 zip 安装的

**Comment by KainanSu** [comment]
@extrastu 从chrome商店安装的

**Comment by extrastu** [comment]
好的，你可以试试下载 zip 自己导入下看看 https://github.com/extrastu/side-browser-release/releases/tag/1.0.3 @KainanSu

**Comment by KainanSu** [comment]
@extrastu 试了一下，导入zip也是上面的效果，看了下插件信息，有下面这些报错
![image](https://github.com/extrastu/side-browser-release/assets/42830139/2a3326a8-a91f-43c5-a548-a96296485bab)

**Comment by extrastu** [comment]
呃呃，应该是当前版本的edge 还不支持，需要你下个 edge 的测试版 @KainanSu 或者直接使用 chrome 吧
