### ISSUE TITLE
添加暗黑模式适配以及插件内打开新标签

### ISSUE THREAD

**Issue by GEEKCX** [extrastu/side-browser-release#3]
希望能加入一个暗黑模式切换icon
还有一点小建议，可以加入一个设置："新标签"是否在插件内的浏览器内打开，还是全局浏览器打开

**Comment by GEEKCX** [comment]
侧边栏浏览器好像对已经安装过的插件不生效？

**Comment by extrastu** [comment]
> 侧边栏浏览器好像对已经安装过的插件不生效？

不是很明白，麻烦详细描述下

**Comment by extrastu** [comment]
> 希望能加入一个暗黑模式切换icon 还有一点小建议，可以加入一个设置："新标签"是否在插件内的浏览器内打开，还是全局浏览器打开

主题切换可行，新标签？

**Comment by GEEKCX** [comment]
> > 希望能加入一个暗黑模式切换icon 还有一点小建议，可以加入一个设置："新标签"是否在插件内的浏览器内打开，还是全局浏览器打开
> 
> 主题切换可行，新标签？

新标签的意思是：
![image](https://github.com/extrastu/side-browser-release/assets/31879429/22ff6b9c-e812-441a-bc0e-4ddb667676e6)
在侧边栏中鼠标右键选择插件无效果，不知道插件能不能在侧边栏中使用。
![image](https://github.com/extrastu/side-browser-release/assets/31879429/b6557a2b-7f19-4c47-9eb1-af2de9883c82)
